<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="7" passed="0" failed="1" skipped="6">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-04-25T15:20:53Z" name="Mail" finished-at="2018-04-25T15:21:10Z" duration-ms="17306">
    <groups>
      <group name="basic-functions">
        <method signature="CreateDraftTest.createMessage(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:mail.tests.CreateDraftTest@4470f8a6]" name="createMessage" class="mail.tests.CreateDraftTest"/>
        <method signature="LoginTest.login()[pri:0, instance:mail.tests.LoginTest@484970b0]" name="login" class="mail.tests.LoginTest"/>
      </group> <!-- basic-functions -->
      <group name="other-functions">
        <method signature="LogOutTest.logOut()[pri:10, instance:mail.tests.LogOutTest@60015ef5]" name="logOut" class="mail.tests.LogOutTest"/>
        <method signature="SendLetterTest.sendLetter(java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:mail.tests.SendLetterTest@37f1104d]" name="sendLetter" class="mail.tests.SendLetterTest"/>
        <method signature="TransferDraft.trancferDrafts(java.lang.String, java.lang.String, java.lang.String)[pri:4, instance:mail.tests.TransferDraft@55740540]" name="trancferDrafts" class="mail.tests.TransferDraft"/>
        <method signature="VerifyDraftsTests.verifyDraft(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:mail.tests.VerifyDraftsTests@7c83dc97]" name="verifyDraft" class="mail.tests.VerifyDraftsTests"/>
      </group> <!-- other-functions -->
    </groups>
    <test started-at="2018-04-25T15:20:53Z" name="TestMail1" finished-at="2018-04-25T15:21:10Z" duration-ms="17306">
      <class name="mail.tests.TransferDraft">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:mail.tests.TransferDraft@55740540]" started-at="2018-04-25T18:21:10Z" name="beforeClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="trancferDrafts(java.lang.String, java.lang.String, java.lang.String)[pri:4, instance:mail.tests.TransferDraft@55740540]" started-at="2018-04-25T18:21:10Z" name="trancferDrafts" data-provider="letterData" depends-on-groups="basic-functions" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TransferDraft.trancferDrafts(java.lang.String, java.lang.String, java.lang.String)[pri:4, instance:mail.tests.TransferDraft@55740540] depends on not successfully finished methods in group "basic-functions"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TransferDraft.trancferDrafts(java.lang.String, java.lang.String, java.lang.String)[pri:4, instance:mail.tests.TransferDraft@55740540] depends on not successfully finished methods in group "basic-functions"at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- trancferDrafts -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:mail.tests.TransferDraft@55740540]" started-at="2018-04-25T18:21:10Z" name="afterClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- mail.tests.TransferDraft -->
      <class name="mail.tests.LogOutTest">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:mail.tests.LogOutTest@60015ef5]" started-at="2018-04-25T18:21:10Z" name="beforeClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="logOut()[pri:10, instance:mail.tests.LogOutTest@60015ef5]" started-at="2018-04-25T18:21:10Z" name="logOut" depends-on-groups="basic-functions" finished-at="2018-04-25T18:21:10Z" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method LogOutTest.logOut()[pri:10, instance:mail.tests.LogOutTest@60015ef5] depends on not successfully finished methods in group "basic-functions"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method LogOutTest.logOut()[pri:10, instance:mail.tests.LogOutTest@60015ef5] depends on not successfully finished methods in group "basic-functions"at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logOut -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:mail.tests.LogOutTest@60015ef5]" started-at="2018-04-25T18:21:10Z" name="afterClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- mail.tests.LogOutTest -->
      <class name="mail.tests.CreateDraftTest">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:mail.tests.CreateDraftTest@4470f8a6]" started-at="2018-04-25T18:21:08Z" name="beforeClass" finished-at="2018-04-25T18:21:10Z" duration-ms="2279" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[hub]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Command duration or timeout: 2.26 seconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Command duration or timeout: 2.26 secondsat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:476)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)at mail.tests.BasicTestClass.beforeClass(BasicTestClass.java:42)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'System info: host: 'EPRURYAW0060', ip: '10.19.10.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'Driver info: driver.version: unknownat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)at java.lang.Thread.run(Unknown Source)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="createMessage(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:mail.tests.CreateDraftTest@4470f8a6]" started-at="2018-04-25T18:21:10Z" name="createMessage" data-provider="letterData" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Command duration or timeout: 2.26 seconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Command duration or timeout: 2.26 secondsat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:476)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)at mail.tests.BasicTestClass.beforeClass(BasicTestClass.java:42)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'System info: host: 'EPRURYAW0060', ip: '10.19.10.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'Driver info: driver.version: unknownat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)at java.lang.Thread.run(Unknown Source)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMessage -->
        <test-method signature="createMessage(java.lang.String, java.lang.String, java.lang.String)[pri:1, instance:mail.tests.CreateDraftTest@4470f8a6]" started-at="2018-04-25T18:21:10Z" name="createMessage" data-provider="letterData" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Command duration or timeout: 2.26 seconds]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Command duration or timeout: 2.26 secondsat java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$new$0(JsonWireProtocolResponse.java:53)at org.openqa.selenium.remote.JsonWireProtocolResponse.lambda$getResponseFunction$2(JsonWireProtocolResponse.java:91)at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:476)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:209)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:132)at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:145)at mail.tests.BasicTestClass.beforeClass(BasicTestClass.java:42)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:451)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:163)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)Caused by: org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Failed to connect to /10.19.10.150:5557Build info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'System info: host: 'EPRURYAW0060', ip: '10.19.10.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'Driver info: driver.version: unknownat org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:118)at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)at java.lang.Thread.run(Unknown Source)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createMessage -->
        <test-method is-config="true" signature="deleteDrafts()[pri:0, instance:mail.tests.CreateDraftTest@4470f8a6]" started-at="2018-04-25T18:21:10Z" name="deleteDrafts" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteDrafts -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:mail.tests.CreateDraftTest@4470f8a6]" started-at="2018-04-25T18:21:10Z" name="afterClass" finished-at="2018-04-25T18:21:10Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- mail.tests.CreateDraftTest -->
      <class name="mail.tests.SendLetterTest">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:mail.tests.SendLetterTest@37f1104d]" started-at="2018-04-25T18:21:10Z" name="beforeClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="sendLetter(java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:mail.tests.SendLetterTest@37f1104d]" started-at="2018-04-25T18:21:10Z" name="sendLetter" data-provider="FillLetter" depends-on-groups="basic-functions" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SendLetterTest.sendLetter(java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:mail.tests.SendLetterTest@37f1104d] depends on not successfully finished methods in group "basic-functions"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SendLetterTest.sendLetter(java.lang.String, java.lang.String, java.lang.String)[pri:3, instance:mail.tests.SendLetterTest@37f1104d] depends on not successfully finished methods in group "basic-functions"at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendLetter -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:mail.tests.SendLetterTest@37f1104d]" started-at="2018-04-25T18:21:10Z" name="afterClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- mail.tests.SendLetterTest -->
      <class name="mail.tests.VerifyDraftsTests">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:mail.tests.VerifyDraftsTests@7c83dc97]" started-at="2018-04-25T18:21:10Z" name="beforeClass" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:mail.tests.VerifyDraftsTests@7c83dc97]" started-at="2018-04-25T18:21:10Z" name="setUp" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyDraft(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:mail.tests.VerifyDraftsTests@7c83dc97]" started-at="2018-04-25T18:21:10Z" name="verifyDraft" data-provider="FillLetter" depends-on-groups="basic-functions" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method VerifyDraftsTests.verifyDraft(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:mail.tests.VerifyDraftsTests@7c83dc97] depends on not successfully finished methods in group "basic-functions"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method VerifyDraftsTests.verifyDraft(java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:mail.tests.VerifyDraftsTests@7c83dc97] depends on not successfully finished methods in group "basic-functions"at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:878)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyDraft -->
        <test-method is-config="true" signature="deleteDrafts()[pri:0, instance:mail.tests.VerifyDraftsTests@7c83dc97]" started-at="2018-04-25T18:21:10Z" name="deleteDrafts" finished-at="2018-04-25T18:21:10Z" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteDrafts -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:mail.tests.VerifyDraftsTests@7c83dc97]" started-at="2018-04-25T18:21:10Z" name="afterClass" finished-at="2018-04-25T18:21:10Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- mail.tests.VerifyDraftsTests -->
      <class name="mail.tests.LoginTest">
        <test-method is-config="true" signature="beforeClass(java.lang.String)[pri:0, instance:mail.tests.LoginTest@484970b0]" started-at="2018-04-25T18:20:53Z" name="beforeClass" finished-at="2018-04-25T18:20:57Z" duration-ms="4582" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[hub]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="login()[pri:0, instance:mail.tests.LoginTest@484970b0]" started-at="2018-04-25T18:20:57Z" name="login" finished-at="2018-04-25T18:21:08Z" duration-ms="10335" status="FAIL">
          <exception class="org.openqa.selenium.NoSuchWindowException">
            <message>
              <![CDATA[no such window: target window already closedfrom unknown error: web view not found  (Session info: chrome=65.0.3325.181)  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 0 millisecondsBuild info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'System info: host: 'EPRURYAW0060', ip: '10.19.10.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'Driver info: org.openqa.selenium.remote.RemoteWebDriverCapabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\IGOR_M~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.181, webStorageEnabled: true, webdriver.remote.sessionid: ce3f9b56163d98f0aef00de7530...}Session ID: ce3f9b56163d98f0aef00de7530ab2a9]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchWindowException: no such window: target window already closedfrom unknown error: web view not found  (Session info: chrome=65.0.3325.181)  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 10.0.15063 x86_64) (WARNING: The server did not provide any stacktrace information)Command duration or timeout: 0 millisecondsBuild info: version: '3.11.0', revision: 'e59cfb3', time: '2018-03-11T20:26:55.152Z'System info: host: 'EPRURYAW0060', ip: '10.19.10.150', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '9.0.4'Driver info: org.openqa.selenium.remote.RemoteWebDriverCapabilities {acceptInsecureCerts: false, acceptSslCerts: false, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.37.544315 (730aa6a5fdba15..., userDataDir: C:\Users\IGOR_M~1\AppData\L...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: XP, platformName: XP, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 65.0.3325.181, webStorageEnabled: true, webdriver.remote.sessionid: ce3f9b56163d98f0aef00de7530...}Session ID: ce3f9b56163d98f0aef00de7530ab2a9at jdk.internal.reflect.GeneratedConstructorAccessor11.newInstance(Unknown Source)at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:545)at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:602)at org.openqa.selenium.remote.RemoteWebDriver.getTitle(RemoteWebDriver.java:277)at mail.pages.main.InboxPage.isTitleLoad(InboxPage.java:19)at mail.tests.LoginTest.login(LoginTest.java:10)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:564)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchWindowException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:mail.tests.LoginTest@484970b0]" started-at="2018-04-25T18:21:08Z" name="afterClass" finished-at="2018-04-25T18:21:08Z" duration-ms="31" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- mail.tests.LoginTest -->
    </test> <!-- TestMail1 -->
  </suite> <!-- Mail -->
</testng-results>
